// FILE: vulcanLogoPath.ts
// Purpose: Shared SVG path data for the Vulcan mark.
// Generated by scripts/generate-brand-mark.py -- do not edit by hand.

export const VULCAN_LOGO_PATHS = [
  "M20 162L146 86L450 86L450 172L318 172L306 288L380 288L406 418L108 418L134 288L208 288L196 172L66 172Z",
] as const;
