#!/usr/bin/env python3
"""Generate the Vulcan brand mark and every icon variant from one geometry source.

The mark is an original anvil silhouette drawn as a single closed polygon. It
deliberately uses only straight edges so that the SVG path and the rasterised
PNG/ICO icons are generated from identical coordinates and cannot drift apart.

Run from the repository root:

    python3 scripts/generate-brand-mark.py

Outputs (all overwritten):
    assets/prod/logo.svg
    apps/web/public/vulcan-logo.svg
    apps/web/src/assets/vulcanLogoPath.ts
    assets/prod/*.png, assets/prod/*.ico
    assets/dev/*.png, assets/dev/*.ico
    apps/web/public/vulcan.png
    apps/desktop/resources/vulcan.png
"""

from __future__ import annotations

import os
from PIL import Image, ImageDraw

# --- Geometry -----------------------------------------------------------------
# Authored in the 470x504 viewBox the inline <VulcanLogo> component uses, so the
# React component's viewBox never has to change. Clockwise from the horn tip.
VIEWBOX_W, VIEWBOX_H = 470, 504

ANVIL = [
    (20, 162),   # horn tip
    (146, 86),   # horn top meets the face
    (450, 86),   # face, top right
    (450, 172),  # face, bottom right
    (318, 172),  # underside of the face, right of the waist
    (306, 288),  # waist, right
    (380, 288),  # base, top right
    (406, 418),  # base, bottom right (flared)
    (108, 418),  # base, bottom left (flared)
    (134, 288),  # base, top left
    (208, 288),  # waist, left
    (196, 172),  # underside of the face, left of the waist
    (66, 172),   # horn underside
]

# --- SVG ----------------------------------------------------------------------


def svg_path() -> str:
    head = f"M{ANVIL[0][0]} {ANVIL[0][1]}"
    rest = "".join(f"L{x} {y}" for x, y in ANVIL[1:])
    return f"{head}{rest}Z"


def write_svg_files(path_data: str) -> None:
    plain = (
        f'<svg width="{VIEWBOX_W}" height="{VIEWBOX_H}" '
        f'viewBox="0 0 {VIEWBOX_W} {VIEWBOX_H}" fill="none" '
        f'xmlns="http://www.w3.org/2000/svg">\n'
        f'<path d="{path_data}" fill="black"/>\n'
        f"</svg>\n"
    )
    _write("assets/prod/logo.svg", plain)

    themed = (
        f'<svg width="{VIEWBOX_W}" height="{VIEWBOX_H}" '
        f'viewBox="0 0 {VIEWBOX_W} {VIEWBOX_H}" fill="none" '
        f'xmlns="http://www.w3.org/2000/svg">\n'
        "<style>\n"
        "  .vulcan-logo-fill { fill: #1c2933; }\n"
        "  @media (prefers-color-scheme: dark) {\n"
        "    .vulcan-logo-fill { fill: #f5f5f5; }\n"
        "  }\n"
        "</style>\n"
        f'<path class="vulcan-logo-fill" d="{path_data}"/>\n'
        f"</svg>\n"
    )
    _write("apps/web/public/vulcan-logo.svg", themed)

    module = (
        "// FILE: vulcanLogoPath.ts\n"
        "// Purpose: Shared SVG path data for the Vulcan mark.\n"
        "// Generated by scripts/generate-brand-mark.py -- do not edit by hand.\n"
        "\n"
        "export const VULCAN_LOGO_PATHS = [\n"
        f'  "{path_data}",\n'
        "] as const;\n"
    )
    _write("apps/web/src/assets/vulcanLogoPath.ts", module)


def _write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(contents)
    print(f"wrote {path}")


# --- Raster -------------------------------------------------------------------

SUPERSAMPLE = 8
MARK_COVERAGE = 0.68  # fraction of the icon's shorter edge the mark spans

# The mark's visual bounding box, which is what should be centred -- not the
# viewBox, whose padding is asymmetric.
MARK_X0 = min(x for x, _ in ANVIL)
MARK_X1 = max(x for x, _ in ANVIL)
MARK_Y0 = min(y for _, y in ANVIL)
MARK_Y1 = max(y for _, y in ANVIL)


def _scaled_polygon(size: int) -> list[tuple[float, float]]:
    mark_w = MARK_X1 - MARK_X0
    mark_h = MARK_Y1 - MARK_Y0
    scale = size * MARK_COVERAGE / max(mark_w, mark_h)
    offset_x = (size - mark_w * scale) / 2
    offset_y = (size - mark_h * scale) / 2
    return [
        ((x - MARK_X0) * scale + offset_x, (y - MARK_Y0) * scale + offset_y)
        for x, y in ANVIL
    ]


def render(size: int, *, circular: bool) -> Image.Image:
    hi = size * SUPERSAMPLE
    image = Image.new("RGBA", (hi, hi), (255, 255, 255, 0))
    draw = ImageDraw.Draw(image)
    if circular:
        draw.ellipse((0, 0, hi - 1, hi - 1), fill=(255, 255, 255, 255))
    else:
        draw.rectangle((0, 0, hi, hi), fill=(255, 255, 255, 255))
    draw.polygon(_scaled_polygon(hi), fill=(0, 0, 0, 255))
    return image.resize((size, size), Image.LANCZOS)


PNG_TARGETS = [
    ("assets/prod/black-macos-1024.png", 1024, False),
    ("assets/prod/black-macos-legacy-1024.png", 1024, True),
    ("assets/prod/black-universal-1024.png", 1024, False),
    ("assets/prod/black-ios-1024.png", 1024, False),
    ("assets/prod/vulcan-black-web-apple-touch-180.png", 180, False),
    ("assets/prod/vulcan-black-web-favicon-32x32.png", 32, False),
    ("assets/prod/vulcan-black-web-favicon-16x16.png", 16, False),
    ("assets/dev/blueprint-macos-1024.png", 1024, False),
    ("assets/dev/blueprint-universal-1024.png", 1024, False),
    ("assets/dev/blueprint-ios-1024.png", 1024, False),
    ("assets/dev/blueprint-web-apple-touch-180.png", 180, False),
    ("assets/dev/blueprint-web-favicon-32x32.png", 32, False),
    ("assets/dev/blueprint-web-favicon-16x16.png", 16, False),
    ("apps/web/public/vulcan.png", 1024, False),
    ("apps/desktop/resources/vulcan.png", 1024, False),
]

ICO_TARGETS = [
    "assets/prod/vulcan-black-windows.ico",
    "assets/prod/vulcan-black-web-favicon.ico",
    "assets/dev/blueprint-windows.ico",
    "assets/dev/blueprint-web-favicon.ico",
]


def write_raster_files() -> None:
    for path, size, circular in PNG_TARGETS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        render(size, circular=False if not circular else True).save(path)
        print(f"wrote {path} ({size}x{size})")

    master = render(256, circular=False)
    for path in ICO_TARGETS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        master.save(path, sizes=[(256, 256)])
        print(f"wrote {path}")


if __name__ == "__main__":
    data = svg_path()
    write_svg_files(data)
    write_raster_files()
